### PR TITLE
Adopt scala library release GHA workflow

### PR DESCRIPTION
**Pull request by emdash-ie**
Following [the example from play-secret-rotation](https://github.com/guardian/play-secret-rotation/pull/416), rather than set up a new developer credential to release the next version of this library, this change sets up [guardian/gha-scala-library-release-workflow](https://github.com/guardian/gha-scala-library-release-workflow).

### CODE REVIEW

**Comment by emdash-ie** [comment]
I have removed branch protections, but I don’t think I have the required github access to grant this repo access to the necessary secrets.

**Comment by rtyley** [comment]
I'm going to review this PR now - may have a few small extra changes to make, the best example PR for adopting `gha-scala-library-release-workflow` at the moment is https://github.com/guardian/facia-scala-client/pull/299, I'll add the appropriate changes that I see...

> I have removed branch protections, but I don’t think I have the required github access to grant this repo access to the necessary secrets – I will try and find out who does.

You'll need a PR like https://github.com/guardian/github-secret-access/pull/21 (but for `guardian/marley` rather than `guardian/facia-scala-client`) to get the access automatically added!

**Comment by rtyley** [comment]
These are a few more tweaks I've added with d26aa63408d0c165af2aa06308c360d45b602705:

* Delete the entire `sonatype.sbt` file that was providing these keys that `gha-scala-library-release-workflow` now takes care of for us:
  * `sonatypeProfileName` - see https://github.com/guardian/gha-scala-library-release-workflow/blob/7d278d4d44e30b4b4c0f6791053bdeb40b8159cb/.github/workflows/reusable-release.yml#L258
  * `publishTo` - see https://github.com/guardian/facia-scala-client/pull/299#discussion_r1425633284
  * `scmInfo` & `pomExtra` - see https://github.com/guardian/facia-scala-client/pull/299#pullrequestreview-1780102876
  * `homepage` - https://github.com/xerial/sbt-sonatype/blob/da75ed2efe29e7d674a6d6af5103b4aa1cecefb8/src/main/scala/xerial/sbt/Sonatype.scala#L368
* Specify Java 11-compatible bytecode - see https://github.com/guardian/facia-scala-client/pull/299/files#r1425630691

As part of some of these changes, I've also removed the vestiges of the build-configuration that adapted the build for Scala 2.11 & 2.12 (eg the `versionDependent()` helper method) - these are no longer need since https://github.com/guardian/marley/pull/78 removed support for Scala 2.12 in January 2023.

**Review by rtyley — APPROVED** [review]
I think this is good to go now, you just need to raise a PR on https://github.com/guardian/github-secret-access to get the credentials added!

**Comment by rtyley** [comment]
I can see this made a ✨  successful release with [v0.2.19](https://github.com/guardian/marley/releases/tag/v0.2.19) ✨  - well done!

**Comment by emdash-ie** [comment]
> I can see this made a ✨ successful release with [v0.2.19](https://github.com/guardian/marley/releases/tag/v0.2.19) ✨ - well done!

I had a question about that actually: there’s a github release with the right version number, but I can’t see that version [in maven](https://mvnrepository.com/artifact/com.gu/marley). Does that suggest something’s not working correctly?

I saw that [in the sonatype release step](https://github.com/guardian/marley/actions/runs/7246621251/job/19739004348) there’re a lot of mentions of “marley 0.1.0-SNAPSHOT”, and wondered if there was a problem picking up the version.

Hmm, thinking about it now I looked for it on sonatype and found this: https://central.sonatype.com/artifact/com.gu/marley_2.13, which looks promising! I don’t really know enough about how maven and sonatype interact, maybe there’s a delay in indexing.

**Comment by emdash-ie** [comment]
Also, I have been assuming that https://mvnrepository.com/ is an “official” maven repository or something like that, which it doesn’t appear to be. I’ll have to do some reading. Since we can see the dependency [on https://central.sonatype.com](https://central.sonatype.com/artifact/com.gu/marley_2.13), I assume everything’s fine.

**Comment by rtyley** [comment]
> Looks like something just a bit flakey in the CDN or webserver responsible for https://repo1.maven.org/maven2/com/gu/marley_2.13/ ?!

Note also that I can break-the-cache - and therefore fix-the-page - by adding a random query parameter to the url:


https://repo1.maven.org/maven2/com/gu/marley_2.13/?foo=bar - **WORKS**

image

https://repo1.maven.org/maven2/com/gu/marley_2.13/ - still fails for everyone
image

Probably the de-caching of this url failed?

**Comment by emdash-ie** [comment]
Ah, thank you for the very thorough explanation!

> I think it's probably worth just kicking off another release to see what happens?!

As in: run the release workflow again, which I suppose will generate v0.2.20 which is identical to v0.2.19? I’m not sure I like the sound of that – I guess it’s not particularly important, but I’d like each release to differ. (Unless running it again with no changes will just redeploy the same release? But then I’m not sure about that either.)

> but this is only because the version number printed here has no technical effect.

Ah yes, I wondered if that was the case.

> I agree it's confusing, and for that alone it should probably be fixed.

Would it be worth setting the version string to “this-version-string-is-irrelevant”? (If that’s possible.) Having the correct number there could also be confusing if it suggests the number matters.

**Comment by rtyley** [comment]
> As in: run the release workflow again, which I suppose will generate v0.2.20 which is identical to v0.2.19? I’m not sure I like the sound of that – I guess it’s not particularly important, but I’d like each release to differ.

Oh, you would _not_ like how I've been testing `gha-scala-library-release-workflow` 😀 

Right now, thanks to Scala Steward's batching settings, I personally don't feel too bad about releasing lots of 'version-bump-patch' releases that are completely empty - I don't want to create too much noise for my fellow devs, but that's about my only concern, and I do need to do lots of releases to check the release workflow. Considering things didn't go perfectly with v0.2.19 I'd be tempted to do another one, just to get a completely successful run.

Still, so long as you can successfully _use_ v0.2.19, I don't think that clean slate of a release run is really that important!


> Would it be worth setting the version string to “this-version-string-is-irrelevant”? (If that’s possible.) Having the correct number there could also be confusing if it suggests the number matters.

That's a good point - it looks like the description string can be set with the [`sonatypeSessionName`](https://github.com/xerial/sbt-sonatype/blob/74881d17843e010953b269d6b7ce9078fcf3c0fb/src/main/scala/xerial/sbt/Sonatype.scala#L140) sbt key, so it could be set to something reasonable. I'm just not entirely sure if it's in some way desirable to have a consistent key, or if the key really should have the _correct_ version in, because there might be some [relevant recovery/clean-up logic](https://github.com/xerial/sbt-sonatype/blob/210b275772770794c45fe57e5267d8296558c1d4/README.md?plain=1#L10) associated with it...

**Comment by emdash-ie** [comment]
> > As in: run the release workflow again, which I suppose will generate v0.2.20 which is identical to v0.2.19? I’m not sure I like the sound of that – I guess it’s not particularly important, but I’d like each release to differ.
> 
> Oh, you would _not_ like how I've been testing `gha-scala-library-release-workflow` 😀

Oh no 😅 

> Right now, thanks to Scala Steward's batching settings, I personally don't feel too bad about releasing lots of 'version-bump-patch' releases that are completely empty - I don't want to create too much noise for my fellow devs, but that's about my only concern, and I do need to do lots of releases to check the release workflow. Considering things didn't go perfectly with v0.2.19 I'd be tempted to do another one, just to get a completely successful run.

Ok, that’s a good point – I’ll do another release.

**Pull request merged**
